# Generated by Django 6.0.6 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('depart_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('course', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
