# Generated by Django 6.0.6 on 2026-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='fees_paid',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
